// Output categories (the CLI's first argument) and the canvas sizes each accepts.

export const SIZES = {
  // App Store Connect. 6.9" is the one size Apple requires for iPhone today.
  'iphone-6.9': { w: 1320, h: 2868, label: 'iPhone 6.9" (App Store, required)' },
  'iphone-6.7': { w: 1290, h: 2796, label: 'iPhone 6.7"' },
  'iphone-6.5': { w: 1284, h: 2778, label: 'iPhone 6.5"' },
  'iphone-6.3': { w: 1206, h: 2622, label: 'iPhone 6.3"' },
  'iphone-5.5': { w: 1242, h: 2208, label: 'iPhone 5.5"' },
  'ipad-13': { w: 2064, h: 2752, label: 'iPad 13" (App Store, required for iPad apps)', frame: 'tablet' },
  'ipad-12.9': { w: 2048, h: 2732, label: 'iPad Pro 12.9"', frame: 'tablet' },
  // Google Play
  'play-phone': { w: 1080, h: 1920, label: 'Google Play phone' },
  'play-tablet': { w: 1600, h: 2560, label: 'Google Play 10" tablet', frame: 'tablet' },
  'play-feature': { w: 1024, h: 500, label: 'Google Play feature graphic' },
  // Social
  og: { w: 1200, h: 630, label: 'Open Graph / link preview' },
  'x-post': { w: 1600, h: 900, label: 'X / Twitter post' },
  linkedin: { w: 1200, h: 627, label: 'LinkedIn post' },
  'ig-square': { w: 1080, h: 1080, label: 'Instagram square' },
  'ig-portrait': { w: 1080, h: 1350, label: 'Instagram portrait' },
  story: { w: 1080, h: 1920, label: 'Story / Reel / TikTok' },
  'yt-thumb': { w: 1280, h: 720, label: 'YouTube thumbnail' },
  'product-hunt': { w: 1270, h: 760, label: 'Product Hunt gallery' },
  dribbble: { w: 1600, h: 1200, label: 'Dribbble shot' },
  // Video
  reel: { w: 1080, h: 1920, label: 'Vertical 1080×1920' },
  landscape: { w: 1920, h: 1080, label: 'Landscape 1080p' },
  square: { w: 1080, h: 1080, label: 'Square 1080' },
  'app-preview': { w: 886, h: 1920, label: 'App Store app preview (6.9"/6.5")', preview: true },
  'app-preview-ipad': { w: 1200, h: 1600, label: 'App Store app preview (iPad)', preview: true },
  '4k': { w: 3840, h: 2160, label: 'Landscape 4K' },
  // Mockups
  'mockup-landscape': { w: 2400, h: 1600, label: 'Mockup 3:2' },
  'mockup-square': { w: 2000, h: 2000, label: 'Mockup square' },
  'mockup-portrait': { w: 1600, h: 2000, label: 'Mockup 4:5' },
}

export const CATEGORIES = {
  'app-store': {
    name: 'App Store screenshots',
    blurb: 'A set of store listing screenshots: one per screen, headline + device, sized for App Store Connect or Google Play.',
    kind: 'still',
    set: true,
    uses3d: true,
    defaultSize: 'iphone-6.9',
    sizes: ['iphone-6.9', 'iphone-6.7', 'iphone-6.5', 'iphone-6.3', 'iphone-5.5', 'ipad-13', 'ipad-12.9', 'play-phone', 'play-tablet'],
    defaultTheme: 'stride',
  },
  'social-card': {
    name: 'Social media cards',
    blurb: 'Launch and feature cards for link previews, X, LinkedIn, Instagram and stories.',
    kind: 'still',
    set: false,
    uses3d: true,
    defaultSize: 'og',
    sizes: ['og', 'x-post', 'linkedin', 'ig-square', 'ig-portrait', 'story', 'yt-thumb', 'product-hunt', 'dribbble', 'play-feature'],
    defaultTheme: 'launch',
  },
  'screen-video': {
    name: 'Mobile screens video',
    blurb: '2D motion built from the screens alone — carousels, stacks, scrolls and zoom tours. Accepts screen recordings.',
    kind: 'video',
    set: false,
    uses3d: false,
    defaultSize: 'reel',
    sizes: ['reel', 'landscape', 'square', 'app-preview', 'app-preview-ipad', 'story', 'ig-portrait', '4k'],
    defaultTheme: 'carousel',
    duration: 12,
    fps: 30,
  },
  'device-video': {
    name: '3D device video',
    blurb: 'three.js device showcase: turntables, orbits, reveals and multi-device scenes with your screens on the displays.',
    kind: 'video',
    set: false,
    uses3d: true,
    defaultSize: 'reel',
    sizes: ['reel', 'landscape', 'square', 'story', 'ig-portrait', '4k'],
    defaultTheme: 'turntable',
    duration: 10,
    fps: 30,
  },
  'device-mockup': {
    name: '3D device mockups',
    blurb: 'Hero stills of the 3D devices with your screens: studio, noir, pedestal, lineup. Optional transparent PNG.',
    kind: 'still',
    set: false,
    uses3d: true,
    defaultSize: 'mockup-landscape',
    sizes: ['mockup-landscape', 'mockup-square', 'mockup-portrait', 'og', 'x-post', 'dribbble', 'landscape', '4k'],
    defaultTheme: 'studio',
  },
}
