// 2D motion themes built from the screens alone. Screen recordings work in
// every one of them: each slide plays for the length of its clip.
export default {
  carousel: {
    id: 'carousel',
    name: 'Carousel',
    blurb: 'Flat phones glide past on a dark mesh; the centred one grows while its caption rises in.',
    layout: 'carousel',
    palette: { bg: '#0a0c16', bg2: '#1b2250', bg3: '#43207a', ink: '#ffffff', sub: 'rgba(255,255,255,0.7)', accent: '#7aa2ff', accent2: '#ff7ad9' },
    type: { display: 'jakarta', weight: 800, tracking: -0.04, size: 1.05, highlight: 'gradient' },
    background: { kind: 'mesh', grain: 0.05, vignette: 0.3, seed: 5 },
    device: { mode: 'flat', flat: 'phone', y: 0.62, size: 0.6, gap: 0.5, frame: '#101116' },
    screen: { transition: 'slide' },
    motion: { duration: 12, intro: false, outro: true },
  },

  stack: {
    id: 'stack',
    name: 'Card stack',
    blurb: 'Frameless screens stacked like cards; each beat the top card flicks away to reveal the next.',
    layout: 'stack',
    palette: { bg: '#f6f1e9', bg2: '#efe6d8', bg3: '#e4d6c1', ink: '#1a1a1a', sub: 'rgba(26,26,26,0.65)', accent: '#e4572e', accent2: '#29335c', surface: '#ffffff' },
    type: { display: 'bricolage', body: 'inter', weight: 800, tracking: -0.04, size: 1.05, highlight: 'marker' },
    background: { kind: 'paper', pattern: 'grid', patternColor: '#1a1a1a', patternOpacity: 0.05, patternMask: false },
    device: { mode: 'frameless', y: 0.63, size: 0.6, corner: 0.08, shadow: 0.22 },
    motion: { duration: 12 },
  },

  scroll: {
    id: 'scroll',
    name: 'Long scroll',
    blurb: 'One phone, gently floating, scrolling through tall full-page captures while captions change.',
    layout: 'scroll',
    palette: { bg: '#e8f1ff', bg2: '#f7ecff', bg3: '#ffffff', ink: '#101828', sub: 'rgba(16,24,40,0.64)', accent: '#2e6bff', accent2: '#a855f7' },
    type: { display: 'manrope', body: 'manrope', weight: 800, tracking: -0.04, size: 1.02, highlight: 'color' },
    background: { kind: 'gradient', angle: 170, pattern: 'dots', patternColor: '#2e6bff', patternOpacity: 0.08, grain: 0.03 },
    device: { mode: 'flat', flat: 'phone', y: 0.62, size: 0.66, float: 0.5, frame: '#0f1115' },
    screen: { transition: 'push-up', fit: 'top' },
    motion: { duration: 14 },
    samples: 'tall',
  },

  'zoom-tour': {
    id: 'zoom-tour',
    name: 'Zoom tour',
    blurb: 'Full-bleed screens with Ken Burns zooms into each slide\'s focus point, captions over a scrim.',
    layout: 'zoom-tour',
    palette: { bg: '#07080c', bg2: '#11131b', bg3: '#1d2030', ink: '#ffffff', sub: 'rgba(255,255,255,0.78)', accent: '#ffd23f', accent2: '#ff6b6b' },
    type: { display: 'space-grotesk', body: 'inter', weight: 700, tracking: -0.04, size: 1.1, highlight: 'color', shadow: 0.35 },
    text: { position: 'bottom', margin: 0.06 },
    background: { kind: 'solid' },
    device: { mode: 'frameless', corner: 0, shadow: 0 },
    screen: { transition: 'fade' },
    motion: { duration: 12, captionStyle: 'blur' },
  },

  wall: {
    id: 'wall',
    name: 'Screen wall',
    blurb: 'A tilted wall of every screen drifting in opposite columns behind a frosted title card.',
    layout: 'wall',
    palette: { bg: '#050505', bg2: '#0e0e10', bg3: '#1a1a1f', ink: '#ffffff', sub: 'rgba(255,255,255,0.72)', accent: '#5eead4', accent2: '#818cf8' },
    type: { display: 'syne', body: 'inter', weight: 800, tracking: -0.03, size: 1.1, highlight: 'gradient' },
    background: { kind: 'solid' },
    device: { mode: 'frameless', size: 0.34, corner: 0.08, shadow: 0 },
    wall: { tiltX: 26, tiltZ: -20, cols: 6, speed: 0.06, card: 'rgba(5,5,5,0.66)' },
    motion: { duration: 10 },
  },

  'store-preview': {
    id: 'store-preview',
    name: 'Store preview',
    blurb: 'App Store preview video style: one phone, clean transitions, short captions. Render at app-preview size.',
    layout: 'phone-swap',
    palette: { bg: '#ffffff', bg2: '#f2f4f8', bg3: '#e6eaf2', ink: '#0b0c0f', sub: 'rgba(11,12,15,0.6)', accent: '#0a84ff', accent2: '#5e5ce6' },
    type: { display: 'inter', body: 'inter', weight: 750, tracking: -0.045, size: 1.08, highlight: 'color' },
    background: { kind: 'gradient', angle: 180, grain: 0 },
    device: { mode: 'flat', flat: 'phone', y: 0.62, size: 0.7, frame: '#0b0c0f', float: 0.25, shadow: 0.18 },
    screen: { transition: 'fade' },
    motion: { duration: 20, hold: 0.8 },
  },

  'grid-reveal': {
    id: 'grid-reveal',
    name: 'Grid reveal',
    blurb: 'Screens pop into a grid, collapse into one hero phone, then the tour begins.',
    layout: 'grid-reveal',
    palette: { bg: '#0b1020', bg2: '#101a3a', bg3: '#1b2f6b', ink: '#ffffff', sub: 'rgba(255,255,255,0.7)', accent: '#4ade80', accent2: '#22d3ee' },
    type: { display: 'outfit', body: 'outfit', weight: 700, tracking: -0.035, size: 1.05, highlight: 'gradient' },
    background: { kind: 'radial', cx: 50, cy: 40, pattern: 'grid', patternOpacity: 0.06, grain: 0.04 },
    device: { mode: 'frameless', size: 0.3, y: 0.44, corner: 0.08, shadow: 0.3, heroSize: 0.6, frame: '#0a0a0c' },
    motion: { duration: 12 },
  },
}
